export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ background: "lightblue", padding: "80px" }}>header</header>
        {children}

        <footer style={{ background: "lightgreen", padding: "80px" }}>Footer</footer>
      </body>
    </html>
  )
}
