//nested Layouts
export const metadata = {
    title: 'Product',
    description: 'Generated by Next.js',
}

export default function ProductDetailsLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
            <h2>here we want something common</h2>
        </>
    )
}